"""
Schemas for EvoShield Module 1.
"""

from dataclasses import dataclass
from typing import Any, Dict, Optional


@dataclass
class InputRequest:
    """
    Input received by Module 1.
    """

    data: Any
    input_type: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None


@dataclass
class InputResponse:
    """
    Output generated by Module 1.
    """

    entity_id: str
    entity_type: str
    status: str
    routing_decision: Optional[str]
    metadata: Dict[str, Any]
    validation_errors: list

    def to_dict(self) -> Dict[str, Any]:
        return {
            "entity_id": self.entity_id,
            "entity_type": self.entity_type,
            "status": self.status,
            "routing_decision": self.routing_decision,
            "metadata": self.metadata,
            "validation_errors": self.validation_errors,
        }